### ISSUE TITLE
运行出错，大神是不是忘了放动态库了

### ISSUE THREAD

**Issue by skewed666** [NipGeihou/lua_esurfing#16]
root@MiRouter:/tmp/upload# lua start.lua
lua: module 'md5.core' not found:
        no field package.preload['md5.core']
        no file './md5/core.lua'
        no file '/usr/share/lua/md5/core.lua'
        no file '/usr/share/lua/md5/core/init.lua'
        no file '/usr/lib/lua/md5/core.lua'
        no file '/usr/lib/lua/md5/core/init.lua'
        no file './md5/core.so'
        no file '/usr/lib/lua/md5/core.so'
        no file '/usr/lib/lua/loadall.so'
        no file './md5.so'
        no file '/usr/lib/lua/md5.so'
        no file '/usr/lib/lua/loadall.so'
stack traceback:
        [C]: in function 'require'
        ?: in main chunk
        [C]: in function 'require'
        start.lua:3: in main chunk
        [C]: ?

**Comment by NipGeihou** [comment]
readme的常见问题看一下
