### ISSUE TITLE
有个问题想请大佬解决一下

### ISSUE THREAD

**Issue by 1786178749** [NipGeihou/lua_esurfing#4]
首先感谢大佬的分享，已经用了几天了，有点问题，情况是这样的，我们学校晚上十一点会断电，校园网又是dhcp分配IP的，这就导致每天获取的ip不一样，登陆不了，必须手动更改start.lua的ip才连的上，所以想请大佬把手动填写ip改成自动获取ip，然后再加个掉线检测，不知道可不可以？

**Comment by NipGeihou** [comment]
更新了代码，现在的版本可以自动获取wan口ip了。

**Comment by 1786178749** [comment]
十分感谢！
