### ISSUE TITLE
lua: error loading module 'md5.core' from file '/usr/lib/lua/md5/core.so':

### ISSUE THREAD

**Issue by iscodeeasyornot** [NipGeihou/lua_esurfing#7]
root@FriendlyWrt:/# lua /root/lua_esurfing/bin/start.lua
lua: error loading module 'md5.core' from file '/usr/lib/lua/md5/core.so':
        Error loading shared library /usr/lib/lua/md5/core.so: Exec format error
stack traceback:
        [C]: ?
        [C]: in function 'require'
        ?: in main chunk
        [C]: in function 'require'
        /root/lua_esurfing/bin/start.lua:3: in main chunk
        [C]: ?

md5库从readme结尾给的参考项目里下的，解压后复制到/usr/lib/lua
如果不放md5库，只把md5.lua和json.lua复制到/usr/lib/lua的话就是
root@FriendlyWrt:/# lua /root/lua_esurfing/bin/start.lua
lua: module 'md5.core' not found:
        no field package.preload['md5.core']
        no file './md5/core.lua'
        no file '/usr/share/lua/md5/core.lua'
        no file '/usr/share/lua/md5/core/init.lua'
        no file '/usr/lib/lua/md5/core.lua'
        no file '/usr/lib/lua/md5/core/init.lua'
        no file './md5/core.so'
        no file '/usr/lib/lua/md5/core.so'
        no file '/usr/lib/lua/loadall.so'
        no file './md5.so'
        no file '/usr/lib/lua/md5.so'
        no file '/usr/lib/lua/loadall.so'
stack traceback:
        [C]: in function 'require'
        ?: in main chunk
        [C]: in function 'require'
        /root/lua_esurfing/bin/start.lua:3: in main chunk
        [C]: ?

**Comment by 1786178749** [comment]
链接: https://pan.baidu.com/s/1mkaSdHyZ03XpT5MEveq5XA 提取码: 1111
放入/sur/lib/lua试试

**Comment by iscodeeasyornot** [comment]
> 链接: https://pan.baidu.com/s/1mkaSdHyZ03XpT5MEveq5XA 提取码: 1111
> 放入/sur/lib/lua试试

root@FriendlyWrt:~# lua start.lua
lua: error loading module 'md5.core' from file '/usr/lib/lua/md5/core.so':
        Error relocating /usr/lib/lua/md5/core.so: unsupported relocation type 8
stack traceback:
        [C]: ?
        [C]: in function 'require'
        ?: in main chunk
        [C]: in function 'require'
        start.lua:3: in main chunk
        [C]: ?

还是没法运行

**Comment by 1786178749** [comment]
你是什么架构的

**Comment by iscodeeasyornot** [comment]
> 你是什么架构的

Linux FriendlyWrt 5.4.61 #1 SMP PREEMPT Thu Oct 15 09:38:37 UTC 2020 aarch64 GNU/Linux

**Comment by 1786178749** [comment]
我问一句你是把core.co文件放进lua文件夹，还是把md5文件夹放进lua文件夹了？

**Comment by NipGeihou** [comment]
> > 你是什么架构的
> 
> Linux FriendlyWrt 5.4.61 #1 SMP PREEMPT Thu Oct 15 09:38:37 UTC 2020 aarch64 GNU/Linux

我想应该是项目的md5库不支持你的处理器，我只在7621上测试过，或者你可以试下另外找一个md5的库

**Comment by iscodeeasyornot** [comment]
花点时间重新编译了一份
适用于rk3328，也就是nanopi-r2s的md5库
链接:https://cloud.189.cn/t/Q36B7nFbei2y
